[package]
authors = ["@colinnielsen"]
compiler_version = ">=0.30.0"
name = "sort"
notes = "AMDG"
type = "bin"

[dependencies]
check_shuffle = {tag = "v0.2.1", git = "https://github.com/noir-lang/noir_check_shuffle"}
sort = { tag = "v0.2.3", git = "https://github.com/noir-lang/noir_sort" }