[package]
authors = ["@colinnielsen"]
compiler_version = ">=0.30.0"
name = "sort"
notes = "AMDG"
type = "bin"

[dependencies]
noir_string_search = {tag = "v0.3.2", git = "https://github.com/noir-lang/noir_string_search"}