[package]
authors = ["@colinnielsen"]
compiler_version = ">=0.30.0"
name = "poseidon"
notes = "AMDG"
type = "bin"

[dependencies]
poseidon = {tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon"}